version: "3.9"

services:
  app:
    image: laravelsail/php83-composer
    container_name: planner-app
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_DATABASE: planner_db
      DB_USERNAME: planner_user
      DB_PASSWORD: planner_pass
    command: >
      bash -c "composer install --no-interaction && php artisan key:generate --force && php artisan migrate:fresh --seed && php artisan serve --host=0.0.0.0 --port=8000"

  frontend:
    image: node:20
    container_name: planner-frontend
    working_dir: /srv/app
    volumes:
      - ./:/srv/app
    ports:
      - "3000:3000"
    command: >
      bash -c "yarn install && yarn start --host 0.0.0.0"
