services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    ports:
      - 3000:3000
      - 8000:8000
    tty: true

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: road_safety
    ports:
      - 5432:5432
